services:
  weatherforecast:
    image: ${DOCKER_REGISTRY-}weatherforecast
    build:
      context: .
      dockerfile: WeatherForecast/Dockerfile
    ports:
      - "1121:80"
  
  temperatureservice:
    image: ${DOCKER_REGISTRY-}temperatureservice
    build:
      context: .
      dockerfile: TemperatureService/Dockerfile
  
  weathersummaryservice:
    image: ${DOCKER_REGISTRY-}weathersummaryservice
    build:
      context: .
      dockerfile: WeatherSummaryService/Dockerfile
